* */*: merged with changes from main branch, revision #6092

diff --git a/branches/sdas_v50/sdcc/debugger/mcs51/configure.in b/branches/sdas_v50/sdcc/debugger/mcs51/configure.in
--- a/branches/sdas_v50/sdcc/debugger/mcs51/configure.in
+++ b/branches/sdas_v50/sdcc/debugger/mcs51/configure.in
@@ -24,12 +24,12 @@ AC_LANG_C
 
 # Checking for header files.
 # ===========================================================================
+AC_CHECK_HEADERS(unistd.h sys/wait.h)
 socket_type=unknown
 AC_CHECK_HEADERS(sys/socket.h, socket_type=sys_socket_h)
 if test $socket_type = unknown; then
   AC_CHECK_HEADERS(winsock2.h, socket_type=winsock2_h)
 fi
-
 
 # Checking for functions/libs
 # ===========================================================================
@@ -44,23 +44,38 @@ fi
 # Macro definitions
 # ===========================================================================
 
-# adl_DD_COPT macro checks if the compiler specified as the 1st parameter
-# supports option specified as the 2nd parameter
-# For example: DD_CPORT(CXX, fPIC)
+# Check whether the compiler for the current language is SunPRO.
 
-AC_DEFUN(adl_DD_COPT, [
-AC_CACHE_CHECK(whether $$1 accepts -$2,sdcc_cv_$1$2,
-cat >_test_.c <<EOF
-#include <stdio.h>
-void main(void) {}
-EOF
-$$1 -v -$2 -c _test_.c 1>&5 2>&5
-if test "$?" = "0"; then
-  sdcc_cv_$1$2="yes"
-else
-  sdcc_cv_$1$2="no"
-fi
-rm -f _test_.* a.out)
+AC_DEFUN([bor_IS_SUNPRO],
+[AC_CACHE_CHECK([whether we are using the SunPRO _AC_LANG compiler],
+  [bor_cv_[]_AC_LANG_ABBREV[]_compiler_sunpro],
+  [_AC_COMPILE_IFELSE([AC_LANG_PROGRAM([], [[#if !defined __SUNPRO_C && !defined __SUNPRO_CC
+       choke me
+#endif
+]])],
+    [bor_compiler_sunpro=yes],
+    [bor_compiler_sunpro=no])
+bor_cv_[]_AC_LANG_ABBREV[]_compiler_sunpro=$bor_compiler_sunpro
+])])
+
+# bor_IS_VALID_OPTION macro checks if the current compiler, selected by 
+# AC_LANG, supports option specified as the 1st parameter. The test fails if
+# the compiler returns an error or in case something is writeen to stderr.
+# For example: bor_VALID_OPT(fPIC)
+
+AC_DEFUN([bor_IS_VALID_OPTION],
+[ac_test_[]_AC_LANG_PREFIX[]FLAGS=${[]_AC_LANG_PREFIX[]FLAGS+set}
+bor_save_[]_AC_LANG_PREFIX[]FLAGS=$[]_AC_LANG_PREFIX[]FLAGS
+AC_CACHE_CHECK(whether $_AC_LANG_PREFIX accepts -$1, bor_cv_[]_AC_LANG_ABBREV[]_$1,
+  [bor_save_[]_AC_LANG_ABBREV[]_werror_flag=$ac_[]_AC_LANG_ABBREV[]_werror_flag
+   ac_[]_AC_LANG_ABBREV[]_werror_flag=yes
+   
+   []_AC_LANG_PREFIX[]FLAGS="-$1"
+   AC_COMPILE_IFELSE([AC_LANG_PROGRAM()],
+     [bor_cv_[]_AC_LANG_ABBREV[]_$1=yes],
+     [bor_cv_[]_AC_LANG_ABBREV[]_$1=no])
+   ac_[]_AC_LANG_ABBREV[]_werror_flag=$bor_save_[]_AC_LANG_ABBREV[]_werror_flag])
+   []_AC_LANG_PREFIX[]FLAGS=$bor_save_[]_AC_LANG_PREFIX[]FLAGS
 ])
 
 # This macro expands DIR and assigns it to RET.
@@ -129,35 +144,50 @@ dnl adl_NORMALIZE_DEFINE_UNQUOTED(var, DEFINE, REFERENCE_STRING)
 AC_DEFUN([adl_NORMALIZE_DEFINE_UNQUOTED], [
   ac_ndu=[$]$1
   adl_NORMALIZE_PATH([ac_ndu], [$]$3)
-  AC_DEFINE_UNQUOTED($2, "${ac_ndu}")
+  AC_DEFINE_UNQUOTED($2, "${ac_ndu}", [XXX])
 ])
 
 
 # Checking characteristics of compilers and other programs
 # ===========================================================================
-AC_CACHE_CHECK(whether preprocessor accepts -MM or -M,sdcc_cv_MM,
-echo "#include <stdio.h>" >_test_.c
-echo "" >>_test_.c
-$CPP -v -MM _test_.c 1>&5 2>&5
-if test "$?" = "0"; then
-  sdcc_cv_MM="-MM"
+if test "$ac_cv_c_compiler_gnu" = "yes"; then
+  AC_CACHE_CHECK(whether preprocessor accepts -MM or -M,sdcc_cv_MM,
+  echo "#include <stdio.h>" >_test_.c
+  echo "" >>_test_.c
+  $CPP -v -MM _test_.c 1>&5 2>&5
+  if test "$?" = "0"; then
+    sdcc_cv_MM="-MM"
+  else
+    sdcc_cv_MM="-M"
+  fi
+  rm -f _test_.*)
+
+  # This is the first time when CFLAGS are set/modified!!
+  bor_IS_VALID_OPTION(ggdb)
+  if test "$bor_cv_c_ggdb" = "yes"; then
+    CFLAGS="-ggdb ${CFLAGS}"
+  fi
+
+  bor_IS_VALID_OPTION(pipe)
+  if test "$bor_cv_c_pipe" = "yes"; then
+    CFLAGS="-pipe $CFLAGS"
+  fi
+
+  WALL_FLAG="-Wall"
+  C99_FLAG="--std=c99"
+  MAKEDEP="$CC $sdcc_cv_MM"
 else
-  sdcc_cv_MM="-M"
-fi
-rm -f _test_.*)
-M_OR_MM=$sdcc_cv_MM
-AC_SUBST(M_OR_MM)
-
-# This is the first time when CFLAGS are set/modified!!
-adl_DD_COPT(CC, ggdb)
-if test "$sdcc_cv_CCggdb" = "yes"; then
-  CFLAGS="-ggdb ${CFLAGS}"
+  bor_IS_SUNPRO
+  if test "$bor_cv_c_compiler_sunpro" = "yes"; then
+    CFLAGS="-xO2 $CFLAGS"
+    WALL_FLAG=
+    C99_FLAG="-xc99"
+    MAKEDEP="$CC -xM1"
+  fi
 fi
 
-adl_DD_COPT(CC, pipe)
-if test "$sdcc_cv_CCpipe" = "yes"; then
-  CFLAGS="-pipe $CFLAGS"
-fi
+AC_SUBST(MAKEDEP)
+AC_SUBST(WALL_FLAG)
 
 
 # Set standard installation paths
@@ -194,7 +224,7 @@ AC_SUBST(EXEEXT)
 # sdccconf.h
 ############
 
-AC_DEFINE_UNQUOTED(DIR_SEPARATOR_STRING, "${sdccconf_h_dir_separator}")
+AC_DEFINE_UNQUOTED(DIR_SEPARATOR_STRING, "${sdccconf_h_dir_separator}", [XXX])
 
 # datadir:
 # default: "${prefix}/share"
@@ -205,7 +235,7 @@ adl_NORMALIZE_DEFINE_UNQUOTED(expanded_datadir, DATADIR, sdccconf_h_dir_separato
 norm_lib_dir_suffix=${lib_dir_suffix}
 adl_NORMALIZE_PATH([norm_lib_dir_suffix], [$sdccconf_h_dir_separator])
 AC_DEFINE_UNQUOTED(LIB_DIR_SUFFIX,
-                   DIR_SEPARATOR_STRING "${norm_lib_dir_suffix}")
+                   DIR_SEPARATOR_STRING "${norm_lib_dir_suffix}", [XXX])
 
 
 # Generating output files
diff --git a/branches/sdas_v50/sdcc/sim/ucsim/configure.in b/branches/sdas_v50/sdcc/sim/ucsim/configure.in
--- a/branches/sdas_v50/sdcc/sim/ucsim/configure.in
+++ b/branches/sdas_v50/sdcc/sim/ucsim/configure.in
@@ -1,8 +1,9 @@
 #!/bin/sh
 
 AC_PREREQ(2.60)
-AC_INIT(.version)
-AC_CONFIG_HEADER(ddconfig.h:ddconfig_in.h)
+AC_INIT
+AC_CONFIG_SRCDIR(.version)
+AC_CONFIG_HEADER(ddconfig.h:ddconfig_in.h custom.h:custom_in.h)
 
 AC_PROG_AWK
 
@@ -21,10 +22,10 @@ AC_SUBST(VERSION)
 AC_SUBST(VERSIONHI)
 AC_SUBST(VERSIONLO)
 AC_SUBST(VERSIONP)
-AC_DEFINE_UNQUOTED(VERSIONSTR, "${VERSION}")
-AC_DEFINE_UNQUOTED(VERSIONHI, $VERSIONHI)
-AC_DEFINE_UNQUOTED(VERSIONLO, $VERSIONLO)
-AC_DEFINE_UNQUOTED(VERSIONP, $VERSIONP)
+AC_DEFINE_UNQUOTED(VERSIONSTR, "${VERSION}", [XXX])
+AC_DEFINE_UNQUOTED(VERSIONHI, $VERSIONHI, [XXX])
+AC_DEFINE_UNQUOTED(VERSIONLO, $VERSIONLO, [XXX])
+AC_DEFINE_UNQUOTED(VERSIONP, $VERSIONP, [XXX])
 
 # Some options
 #==============
@@ -99,7 +100,7 @@ if test $enable_statistic != "no"; then
    enable_statistic="yes"
 fi,
 enable_statistic="no")
-AC_DEFINE_UNQUOTED(STATISTIC, $enable_statistic)
+AC_DEFINE_UNQUOTED(STATISTIC, $enable_statistic, [XXX])
 
 
 # Required programs
@@ -119,7 +120,7 @@ AC_SUBST(LIBTOOL_DEPS)
 
 AC_PROG_LEX
 if test ${LEX} = "flex"; then
-        AC_DEFINE(HAVE_FLEX)
+        AC_DEFINE(HAVE_FLEX, 1, [XXX])
 fi
 AC_PROG_YACC
 AC_CHECK_PROG(BISON_PLUS_PLUS, bison++, bison++, :)
@@ -135,28 +136,29 @@ if test -d /stuff/include; then
 fi
 
 AC_HEADER_STDC
+AC_CHECK_HEADERS(endian.h sys/endian.h machine/endian.h sys/isa_defs.h)
 AC_CHECK_HEADERS(getopt.h unistd.h termios.h)
 
 AC_CHECK_HEADER(curses.h,
-  AC_DEFINE(HAVE_CURSES_H)
+  AC_DEFINE(HAVE_CURSES_H, 1, [XXX])
   curses_h_ok=yes,
   curses_h_ok=no
 )
 
 ucsim_cv_socket="unknown"
 AC_CHECK_HEADER(sys/socket.h,
-  AC_DEFINE(HAVE_SYS_SOCKET_H)
-  AC_DEFINE(SOCKET_AVAIL)
-  AC_DEFINE_UNQUOTED(UCSOCKET_T, int)
+  AC_DEFINE(HAVE_SYS_SOCKET_H, 1, [XXX])
+  AC_DEFINE(SOCKET_AVAIL, 1, [XXX])
+  AC_DEFINE_UNQUOTED(UCSOCKET_T, int, [XXX])
   ucsim_cv_socket="<sys/socket.h>"
 )
 
 WINSOCK_AVAIL=0
 if test $ucsim_cv_socket = unknown; then
   AC_CHECK_HEADER(winsock2.h,
-    AC_DEFINE(HAVE_WINSOCK2_H)
-    AC_DEFINE(SOCKET_AVAIL)
-    AC_DEFINE_UNQUOTED(UCSOCKET_T, SOCKET)
+    AC_DEFINE(HAVE_WINSOCK2_H, 1, [XXX])
+    AC_DEFINE(SOCKET_AVAIL, 1, [XXX])
+    AC_DEFINE_UNQUOTED(UCSOCKET_T, SOCKET, [XXX])
     ucsim_cv_socket="<winsock2.h>"
     WINSOCK_AVAIL=1
   )
@@ -166,10 +168,10 @@ AC_SUBST(WINSOCK_AVAIL)
 if test $ucsim_cv_socket != unknown; then
   AC_EGREP_HEADER(socklen_t,
     $ucsim_cv_socket,
-    AC_DEFINE_UNQUOTED(SOCKLEN_T, socklen_t),
-    AC_DEFINE_UNQUOTED(SOCKLEN_T, uint))
+    AC_DEFINE_UNQUOTED(SOCKLEN_T, socklen_t, [XXX]),
+    AC_DEFINE_UNQUOTED(SOCKLEN_T, uint, [XXX]))
 fi
-AC_DEFINE_UNQUOTED(HEADER_SOCKET, ${ucsim_cv_socket})
+AC_DEFINE_UNQUOTED(HEADER_SOCKET, ${ucsim_cv_socket}, [XXX])
 
 AC_CHECK_HEADER(dlfcn.h)
 AC_HEADER_DIRENT
@@ -201,32 +203,32 @@ yes
 
 ucsim_cv_header_ok=0
 if echo $ucsim_cv_fd|grep time >/dev/null 2>&1; then
-AC_DEFINE(FD_NEED_TIME_H, 1)
+AC_DEFINE(FD_NEED_TIME_H, 1, [XXX])
 ucsim_cv_header_ok=1
 else
-AC_DEFINE(FD_NEED_TIME_H, 0)
+AC_DEFINE(FD_NEED_TIME_H, 0, [XXX])
 fi
 if echo $ucsim_cv_fd|grep types >/dev/null 2>&1; then
-AC_DEFINE(FD_NEED_TYPES_H, 1)
+AC_DEFINE(FD_NEED_TYPES_H, 1, [XXX])
 ucsim_cv_header_ok=1
 else
-AC_DEFINE(FD_NEED_TYPES_H, 0)
+AC_DEFINE(FD_NEED_TYPES_H, 0, [XXX])
 fi
 if echo $ucsim_cv_fd|grep select >/dev/null 2>&1; then
-AC_DEFINE(FD_NEED_SELECT_H, 1)
+AC_DEFINE(FD_NEED_SELECT_H, 1, [XXX])
 ucsim_cv_header_ok=1
 else
-AC_DEFINE(FD_NEED_SELECT_H, 0)
+AC_DEFINE(FD_NEED_SELECT_H, 0, [XXX])
 fi
 if echo $ucsim_cv_fd|grep winsock2 >/dev/null 2>&1; then
-AC_DEFINE(FD_NEED_WINSOCK2_H, 1)
+AC_DEFINE(FD_NEED_WINSOCK2_H, 1, [XXX])
 ucsim_cv_header_ok=1
 else
-AC_DEFINE(FD_NEED_WINSOCK2_H, 0)
+AC_DEFINE(FD_NEED_WINSOCK2_H, 0, [XXX])
 fi
 
-AC_DEFINE_UNQUOTED(FD_HEADER_OK, ${ucsim_cv_header_ok})
-AC_DEFINE_UNQUOTED(HEADER_FD, ${ucsim_cv_fd})
+AC_DEFINE_UNQUOTED(FD_HEADER_OK, ${ucsim_cv_header_ok}, [XXX])
+AC_DEFINE_UNQUOTED(HEADER_FD, ${ucsim_cv_fd}, [XXX])
 
 
 # Checking for functions/libs
@@ -326,7 +328,7 @@ ucsim_cv_scanf_a="no",
 ucsim_cv_scanf_a="unknown")
 ])
 if test "$ucsim_cv_scanf_a" = "yes"; then
-  AC_DEFINE(SCANF_A)
+  AC_DEFINE(SCANF_A, 1, [XXX])
 fi
 
 AC_CACHE_CHECK(whether getcwd is GNUish, ucsim_cv_getcwd,
@@ -343,10 +345,10 @@ ucsim_cv_getcwd="no",
 ucsim_cv_getcwd="unknown")
 ])
 if test "$ucsim_cv_getcwd" = "yes"; then
-  AC_DEFINE(GNU_GETCWD)
+  AC_DEFINE(GNU_GETCWD, 1, [XXX])
 fi
 
-AC_DEFUN(ucsim_ACCEPT_LENGTH_T,
+AC_DEFUN([ucsim_ACCEPT_LENGTH_T],
  [AC_CACHE_CHECK([for type of length pointer parameter of accept],
    ucsim_cv_accept_length_type,
    [ac_save_CPPFLAGS="$CPPFLAGS"
@@ -372,48 +374,39 @@ ucsim_ACCEPT_LENGTH_T
 # Macro definitions
 ###################
 
-# DD_COPT macro checks if the compiler specified as the 1st parameter
-# supports option specified as the 2nd parameter
-# For example: DD_COPT(CXX, fPIC)
+# Check whether the compiler for the current language is SunPRO.
 
-AC_DEFUN(DD_COPT, [
-AC_CACHE_CHECK(whether $$1 accepts -$2,ucsim_cv_$1$2,
-cat >_test_.c <<EOF
-int main(void) {return(0);}
-EOF
-$$1 -v -$2 -c _test_.c 1>&5 2>&5
-if test "$?" = "0"; then
-  ucsim_cv_$1$2="yes"
-else
-  ucsim_cv_$1$2="no"
-fi
-rm -f _test_.* a.out)
+AC_DEFUN([bor_IS_SUNPRO],
+[AC_CACHE_CHECK([whether we are using the SunPRO _AC_LANG compiler],
+  [bor_cv_[]_AC_LANG_ABBREV[]_compiler_sunpro],
+  [_AC_COMPILE_IFELSE([AC_LANG_PROGRAM([], [[#if !defined __SUNPRO_C && !defined __SUNPRO_CC
+       choke me
+#endif
+]])],
+    [bor_compiler_sunpro=yes],
+    [bor_compiler_sunpro=no])
+bor_cv_[]_AC_LANG_ABBREV[]_compiler_sunpro=$bor_compiler_sunpro
+])])
+
+# bor_IS_VALID_OPTION macro checks if the current compiler, selected by 
+# AC_LANG, supports option specified as the 1st parameter. The test fails if
+# the compiler returns an error or in case something is writeen to stderr.
+# For example: bor_VALID_OPT(fPIC)
+
+AC_DEFUN([bor_IS_VALID_OPTION],
+[ac_test_[]_AC_LANG_PREFIX[]FLAGS=${[]_AC_LANG_PREFIX[]FLAGS+set}
+bor_save_[]_AC_LANG_PREFIX[]FLAGS=$[]_AC_LANG_PREFIX[]FLAGS
+AC_CACHE_CHECK(whether $_AC_LANG_PREFIX accepts -$1, bor_cv_[]_AC_LANG_ABBREV[]_$1,
+  [bor_save_[]_AC_LANG_ABBREV[]_werror_flag=$ac_[]_AC_LANG_ABBREV[]_werror_flag
+   ac_[]_AC_LANG_ABBREV[]_werror_flag=yes
+   
+   []_AC_LANG_PREFIX[]FLAGS="-$1"
+   AC_COMPILE_IFELSE([AC_LANG_PROGRAM()],
+     [bor_cv_[]_AC_LANG_ABBREV[]_$1=yes],
+     [bor_cv_[]_AC_LANG_ABBREV[]_$1=no])
+   ac_[]_AC_LANG_ABBREV[]_werror_flag=$bor_save_[]_AC_LANG_ABBREV[]_werror_flag])
+   []_AC_LANG_PREFIX[]FLAGS=$bor_save_[]_AC_LANG_PREFIX[]FLAGS
 ])
-
-# DD_COPT_NO_IGNORE macro checks if the compiler specified as the
-# 1st parameter supports and doesn't ignore option specified as the
-# 2nd parameter
-# For example: DD_COPT_NO_IGNORE(CXX, fPIC)
-
-AC_DEFUN(DD_COPT_NO_IGNORE, [
-AC_CACHE_CHECK(whether $$1 accepts and doesn't ignore -$2,ucsim_cv_$1$2,
-cat >_test_.c <<EOF
-int main(void) {return(0);}
-EOF
-ucsim_cv_$1$2=$($$1 -v -$2 -c _test_.c 2>&1 1>&5)
-if test "$?" = "0"; then
-  expr "$ucsim_cv_$1$2" : '.*'-$2'.*ignored' 1>&5 2>&5
-  if test "$?" = "0"; then
-    ucsim_cv_$1$2="no"
-  else
-    ucsim_cv_$1$2="yes"
-  fi
-else
-  ucsim_cv_$1$2="no"
-fi
-rm -f _test_.* a.out)
-])
-
 
 # Checking characteristics of compilers and other programs
 # --------------------------------------------------------
@@ -501,55 +494,62 @@ esac
 
 SDCC_BUILD_BIGENDIAN
 
-AC_CACHE_CHECK(whether preprocessor accepts -MM or -M,ucsim_cv_MM,
-echo "#include <stdio.h>" >_test_.c
-echo "" >>_test_.c
-$CXXCPP -v -MM _test_.c 1>&5 2>&5
-if test "$?" = "0"; then
-  ucsim_cv_MM="-MM"
-else
-  ucsim_cv_MM="-M"
-fi
-rm -f _test_.*)
-M_OR_MM=$ucsim_cv_MM
-AC_SUBST(M_OR_MM)
-
-# This is the first time when CFLAGS are set/modified!!
-
-DD_COPT(CXX, ggdb)
-DD_COPT(CXX, gstabs)
-if test "$ucsim_cv_CXXgstabs" = "yes"; then
-   gopt="-gstabs+ -g3"
-elif test "$ucsim_cv_CXXggdb" = "yes"; then
-     gopt="-ggdb -g3"
-else
-     gopt="-g"
-fi
-if test "$CXXFLAGS"x = x ;then
-        CXXFLAGS="$gopt"
-else
-        CXXFLAGS="$CXXFLAGS $gopt"
-fi
-
-DD_COPT(CXX, pipe)
-if test "$ucsim_cv_CXXpipe" = "yes"; then
-  CXXFLAGS="$CXXFLAGS -pipe"
-fi
-
 PICOPT=""
 SHAREDLIB="no"
-DD_COPT_NO_IGNORE(CXX, fPIC)
-if test "$ucsim_cv_CXXfPIC" = "yes"; then
-    PICOPT="-fPIC"
+
+if test "$ac_cv_cxx_compiler_gnu" = "yes"; then
+  AC_CACHE_CHECK(whether preprocessor accepts -MM or -M,ucsim_cv_MM,
+  echo "#include <stdio.h>" >_test_.c
+  echo "" >>_test_.c
+  $CXXCPP -v -MM _test_.c 1>&5 2>&5
+  if test "$?" = "0"; then
+    ucsim_cv_MM="-MM"
+  else
+    ucsim_cv_MM="-M"
+  fi
+  rm -f _test_.*)
+
+  # This is the first time when CFLAGS are set/modified!!
+
+  bor_IS_VALID_OPTION(ggdb)
+  bor_IS_VALID_OPTION(gstabs)
+  if test "$ucsim_cv_cxx_gstabs" = "yes"; then
+    gopt="-gstabs+ -g3"
+  elif test "$ucsim_cv_cxx_ggdb" = "yes"; then
+    gopt="-ggdb -g3"
+  else
+    gopt="-g"
+  fi
+  if test "$CXXFLAGS"x = x ;then
+    CXXFLAGS="$gopt"
+  else
+    CXXFLAGS="$CXXFLAGS $gopt"
+  fi
+
+  bor_IS_VALID_OPTION(pipe)
+  if test "$ucsim_cv_cxx_pipe" = "yes"; then
+    CXXFLAGS="$CXXFLAGS -pipe"
+  fi
+
+  MAKEDEP="$CXX $ucsim_cv_MM"
+  WALL_FLAG="-Wall"
 else
-    DD_COPT_NO_IGNORE(CXX, fpic)
-    if test "$ucsim_cv_CXXfpic" = "yes"; then
-        PICOPT="-fpic"
-    fi
+  bor_IS_SUNPRO
+  if test "$bor_cv_cxx_compiler_sunpro" = "yes"; then
+    CXXFLAGS="-xO2 $CXXFLAGS"
+    MAKEDEP="$CXX -xM1"
+    WALL_FLAG=
+  fi
 fi
+
+# pic_flag is defined by AC_PROG_LIBTOOL
+PICOPT=$pic_flag
+
 if test "$PICOPT"x != "x"; then
     SHAREDLIB="yes"
 fi
+AC_SUBST(MAKEDEP)
+AC_SUBST(WALL_FLAG)
 AC_SUBST(SHAREDLIB)
 AC_SUBST(PICOPT)
 
@@ -616,9 +616,17 @@ AC_MSG_RESULT($TYPE_WORD)
 AC_MSG_CHECKING(type name for dword)
 TYPE_DWORD=`type_name 4`
 AC_MSG_RESULT($TYPE_DWORD)
-AC_DEFINE_UNQUOTED(TYPE_BYTE, $TYPE_BYTE)
-AC_DEFINE_UNQUOTED(TYPE_WORD, $TYPE_WORD)
-AC_DEFINE_UNQUOTED(TYPE_DWORD, $TYPE_DWORD)
+AC_DEFINE_UNQUOTED(TYPE_BYTE, [$TYPE_BYTE], [XXX])
+AC_DEFINE_UNQUOTED(TYPE_WORD, [$TYPE_WORD], [XXX])
+AC_DEFINE_UNQUOTED(TYPE_DWORD, [$TYPE_DWORD], [XXX])
+AC_DEFINE_UNQUOTED(TYPE_UBYTE, [unsigned $TYPE_BYTE], [XXX])
+AC_DEFINE_UNQUOTED(TYPE_UWORD, [unsigned $TYPE_WORD], [XXX])
+AC_DEFINE_UNQUOTED(TYPE_UDWORD, [unsigned $TYPE_DWORD], [XXX])
+
+AH_TOP([#ifndef DDCONFIG_HEADER
+#define DDCONFIG_HEADER])
+AH_BOTTOM([#include "custom.h"
+#endif /* DDCONFIG_HEADER */])
 
 if echo $TYPE_DWORD|grep short >/dev/null; then
     A="h"
@@ -633,8 +641,8 @@ elif echo $TYPE_WORD|grep long >/dev/null; then M="l"
 else M=""
 fi
 
-AC_DEFINE_UNQUOTED(_A_, "${A}")
-AC_DEFINE_UNQUOTED(_M_, "${M}")
+AC_DEFINE_UNQUOTED(_A_, "${A}", [XXX])
+AC_DEFINE_UNQUOTED(_M_, "${M}", [XXX])
 
 # Generating output files
 # ===========================================================================
