apply changes of trunk from r5165 up to r5812

diff --git a/ucsim-0_6-pre/configure.in b/ucsim-0_6-pre/configure.in
--- a/ucsim-0_6-pre/configure.in
+++ b/ucsim-0_6-pre/configure.in
@@ -1,13 +1,14 @@
 #!/bin/sh
 
+AC_PREREQ(2.60)
 AC_INIT(.version)
 AC_CONFIG_HEADER(ddconfig.h:ddconfig_in.h)
 
 AC_PROG_AWK
 
 AC_MSG_CHECKING(version of the package)
-if test -f .version; then
-  VERSION=`cat .version`
+if test -f ${srcdir}/.version; then
+  { read VERSION; } < ${srcdir}/.version
   AC_MSG_RESULT($VERSION)
 else
   VERSION="0.0.0"
@@ -60,13 +61,13 @@ if test $enable_avr != "no"; then
 fi,
 enable_avr="yes")
 AC_ARG_ENABLE(z80,
-[  --enable-z80            compile simulator for Z80],
+[  --disable-z80           do not compile simulator for Z80],
 if test $enable_z80 != "no"; then
     enable_z80="yes"
 fi,
-enable_z80="no")
+enable_z80="yes")
 AC_ARG_ENABLE(hc08,
-[  --enable-hc08           compile simulator for hc08],
+[  --disable-hc08          do not compile simulator for hc08],
 if test $enable_hc08 != "no"; then
     enable_hc08="yes"
 fi,
@@ -82,7 +83,7 @@ AC_ARG_ENABLE(portmon,
 if test $enable_serio != "no"; then
     enable_serio="yes"
 fi,
-enable_serio="yes")
+enable_serio="no")
 AC_SUBST(enable_ucsim)
 AC_SUBST(enable_dlso)
 AC_SUBST(enable_51)
@@ -118,7 +119,7 @@ AC_SUBST(LIBTOOL_DEPS)
 
 AC_PROG_LEX
 if test ${LEX} = "flex"; then
-	AC_DEFINE(HAVE_FLEX)
+        AC_DEFINE(HAVE_FLEX)
 fi
 AC_PROG_YACC
 AC_CHECK_PROG(BISON_PLUS_PLUS, bison++, bison++, :)
@@ -134,16 +135,43 @@ if test -d /stuff/include; then
 fi
 
 AC_HEADER_STDC
-AC_CHECK_HEADERS(getopt.h)
-AC_CHECK_HEADERS(unistd.h)
-AC_CHECK_HEADER(sys/socket.h,
-    AC_DEFINE(SOCKET_AVAIL)
-    AC_DEFINE(HAVE_SYS_SOCKET_H)
-    AC_EGREP_HEADER(socklen_t,
-		    sys/socket.h,
-		    AC_DEFINE_UNQUOTED(SOCKLEN_T, socklen_t),
-		    AC_DEFINE_UNQUOTED(SOCKLEN_T, uint))
+AC_CHECK_HEADERS(endian.h sys/endian.h machine/endian.h sys/isa_defs.h)
+AC_CHECK_HEADERS(getopt.h unistd.h termios.h)
+
+AC_CHECK_HEADER(curses.h,
+  AC_DEFINE(HAVE_CURSES_H)
+  curses_h_ok=yes,
+  curses_h_ok=no
 )
+
+ucsim_cv_socket="unknown"
+AC_CHECK_HEADER(sys/socket.h,
+  AC_DEFINE(HAVE_SYS_SOCKET_H)
+  AC_DEFINE(SOCKET_AVAIL)
+  AC_DEFINE_UNQUOTED(UCSOCKET_T, int)
+  ucsim_cv_socket="<sys/socket.h>"
+)
+
+WINSOCK_AVAIL=0
+if test $ucsim_cv_socket = unknown; then
+  AC_CHECK_HEADER(winsock2.h,
+    AC_DEFINE(HAVE_WINSOCK2_H)
+    AC_DEFINE(SOCKET_AVAIL)
+    AC_DEFINE_UNQUOTED(UCSOCKET_T, SOCKET)
+    ucsim_cv_socket="<winsock2.h>"
+    WINSOCK_AVAIL=1
+  )
+fi
+AC_SUBST(WINSOCK_AVAIL)
+
+if test $ucsim_cv_socket != unknown; then
+  AC_EGREP_HEADER(socklen_t,
+    $ucsim_cv_socket,
+    AC_DEFINE_UNQUOTED(SOCKLEN_T, socklen_t),
+    AC_DEFINE_UNQUOTED(SOCKLEN_T, uint))
+fi
+AC_DEFINE_UNQUOTED(HEADER_SOCKET, ${ucsim_cv_socket})
+
 AC_CHECK_HEADER(dlfcn.h)
 AC_HEADER_DIRENT
 
@@ -151,6 +179,11 @@ AC_HEADER_DIRENT
 
 AC_CACHE_CHECK(which header file defines FD_ macros, ucsim_cv_fd,
 [ucsim_cv_fd="unknown"
+AC_EGREP_CPP(yes, [
+#include <winsock2.h>
+#ifdef FD_ZERO
+yes
+#endif], ucsim_cv_fd="<winsock2.h>")
 AC_EGREP_CPP(yes, [
 #include <sys/time.h>
 #ifdef FD_ZERO
@@ -165,35 +198,47 @@ AC_EGREP_CPP(yes, [
 #include <sys/select.h>
 #ifdef FD_ZERO
 yes
-#endif], ucsim_cv_fd="<sys/types.h>")])
+#endif], ucsim_cv_fd="<sys/select.h>")])
 
-AC_DEFINE(FD_HEADER_OK, 0)
+ucsim_cv_header_ok=0
 if echo $ucsim_cv_fd|grep time >/dev/null 2>&1; then
 AC_DEFINE(FD_NEED_TIME_H, 1)
-AC_DEFINE(FD_HEADER_OK, 1)
+ucsim_cv_header_ok=1
 else
 AC_DEFINE(FD_NEED_TIME_H, 0)
 fi
 if echo $ucsim_cv_fd|grep types >/dev/null 2>&1; then
 AC_DEFINE(FD_NEED_TYPES_H, 1)
-AC_DEFINE(FD_HEADER_OK, 1)
+ucsim_cv_header_ok=1
 else
 AC_DEFINE(FD_NEED_TYPES_H, 0)
 fi
 if echo $ucsim_cv_fd|grep select >/dev/null 2>&1; then
 AC_DEFINE(FD_NEED_SELECT_H, 1)
-AC_DEFINE(FD_HEADER_OK, 1)
+ucsim_cv_header_ok=1
 else
 AC_DEFINE(FD_NEED_SELECT_H, 0)
 fi
+if echo $ucsim_cv_fd|grep winsock2 >/dev/null 2>&1; then
+AC_DEFINE(FD_NEED_WINSOCK2_H, 1)
+ucsim_cv_header_ok=1
+else
+AC_DEFINE(FD_NEED_WINSOCK2_H, 0)
+fi
 
+AC_DEFINE_UNQUOTED(FD_HEADER_OK, ${ucsim_cv_header_ok})
 AC_DEFINE_UNQUOTED(HEADER_FD, ${ucsim_cv_fd})
 
 
 # Checking for functions/libs
 # ===========================================================================
-AC_CHECK_LIB(socket,socket)
-AC_CHECK_LIB(nsl,xdr_short)
+if echo $ucsim_cv_socket|grep winsock2 >/dev/null 2>&1; then
+  LIBS="-lws2_32 $LIBS"
+else
+  AC_CHECK_LIB(socket,socket)
+  AC_CHECK_LIB(nsl,xdr_short)
+fi
+
 AC_CHECK_LIB(dl,dlopen,
 dl_ok="yes"
 DL="-ldl",
@@ -201,25 +246,55 @@ dl_ok="no"
 DL="")
 AC_SUBST(dl_ok)
 AC_SUBST(DL)
-AC_CHECK_LIB(panel,panel_above,
-panel_ok="yes"
-curses_ok="yes"
-CURSES_LIBS="-lpanel -lcurses"
-,
-panel_ok="no"
-AC_CHECK_LIB(curses,nl,
-curses_ok="yes"
-CURSES_LIBS="-lcurses"
-,
-ncurses_ok="no")
-,
--lcurses)
+
+#AC_CHECK_LIB(panel,panel_above,
+#panel_ok="yes"
+#curses_ok="yes"
+#CURSES_LIBS="-lpanel -lcurses"
+#,
+#panel_ok="no"
+#AC_CHECK_LIB(curses,nl,
+#curses_ok="yes"
+#CURSES_LIBS="-lcurses"
+#,
+#curses_ok="no")
+#,
+#-lcurses)
+
+if test $curses_h_ok != yes; then
+  panel_ok="no"
+  curses_ok="no"
+else
+  AC_CHECK_LIB(panel,panel_above,
+    panel_ok="yes"
+    curses_ok="yes"
+    CURSES_LIBS="-lpanel",
+    panel_ok="no"
+    curses_ok="no"
+  )
+
+  if test $curses_ok != yes; then
+    AC_CHECK_LIB(curses,nl,
+      curses_ok="yes"
+      CURSES_LIBS="-lcurses",
+      curses_ok="no")
+  fi
+
+  if test $curses_ok != yes; then
+    AC_CHECK_LIB(ncurses,nl,
+      curses_ok="yes"
+      CURSES_LIBS="-lncurses",
+      curses_ok="no")
+  fi
+fi
+
 AC_SUBST(panel_ok)
 AC_SUBST(curses_ok)
 AC_SUBST(CURSES_LIBS)
 
 AC_FUNC_VPRINTF
 AC_CHECK_FUNCS(vsnprintf)
+AC_CHECK_FUNCS(_vsnprintf)
 AC_CHECK_FUNCS(vasprintf)
 AC_CHECK_FUNCS(strlen strcpy strcat strstr strcmp strerror strtok strdup)
 AC_CHECK_FUNCS(strchr memcpy)
@@ -280,7 +355,7 @@ AC_DEFUN(ucsim_ACCEPT_LENGTH_T,
     for ac_val in int size_t socklen_t; do
       CPPFLAGS="$ac_save_CPPFLAGS -DACCEPT_SOCKLEN_T=$ac_val"
       AC_TRY_COMPILE([#include <sys/types.h>
-#include <sys/socket.h>],
+#include ${ucsim_cv_socket}],
         [struct sockaddr a; $ac_val len; accept (0, &a, &len);],
         [ucsim_cv_accept_length_type=$ac_val; break])
     done
@@ -298,25 +373,39 @@ ucsim_ACCEPT_LENGTH_T
 # Macro definitions
 ###################
 
-# DD_COPT macro checks if the compiler specified as the 1st parameter
-# supports option specified as the 2nd parameter
-# For example: DD_COPT(CXX, fPIC)
+# Check whether the compiler for the current language is SunPRO.
 
-AC_DEFUN(DD_COPT, [
-AC_CACHE_CHECK(whether $$1 accepts -$2,ucsim_cv_$1$2,
-cat >_test_.c <<EOF
-#include <stdio.h>
-int main(void) {return(0);}
-EOF
-$$1 -v -$2 -c _test_.c 1>&5 2>&5
-if test "$?" = "0"; then
-  ucsim_cv_$1$2="yes"
-else
-  ucsim_cv_$1$2="no"
-fi
-rm -f _test_.* a.out)
+AC_DEFUN(bor_IS_SUNPRO,
+[AC_CACHE_CHECK([whether we are using the SunPRO _AC_LANG compiler],
+  [bor_cv_[]_AC_LANG_ABBREV[]_compiler_sunpro],
+  [_AC_COMPILE_IFELSE([AC_LANG_PROGRAM([], [[#if !defined __SUNPRO_C && !defined __SUNPRO_CC
+       choke me
+#endif
+]])],
+    [bor_compiler_sunpro=yes],
+    [bor_compiler_sunpro=no])
+bor_cv_[]_AC_LANG_ABBREV[]_compiler_sunpro=$bor_compiler_sunpro
+])])
+
+# bor_IS_VALID_OPTION macro checks if the current compiler, selected by 
+# AC_LANG, supports option specified as the 1st parameter. The test fails if
+# the compiler returns an error or in case something is writeen to stderr.
+# For example: bor_VALID_OPT(fPIC)
+
+AC_DEFUN(bor_IS_VALID_OPTION,
+[ac_test_[]_AC_LANG_PREFIX[]FLAGS=${[]_AC_LANG_PREFIX[]FLAGS+set}
+bor_save_[]_AC_LANG_PREFIX[]FLAGS=$[]_AC_LANG_PREFIX[]FLAGS
+AC_CACHE_CHECK(whether $_AC_LANG_PREFIX accepts -$1, bor_cv_[]_AC_LANG_ABBREV[]_$1,
+  [bor_save_[]_AC_LANG_ABBREV[]_werror_flag=$ac_[]_AC_LANG_ABBREV[]_werror_flag
+   ac_[]_AC_LANG_ABBREV[]_werror_flag=yes
+   
+   []_AC_LANG_PREFIX[]FLAGS="-$1"
+   AC_COMPILE_IFELSE([AC_LANG_PROGRAM()],
+     [bor_cv_[]_AC_LANG_ABBREV[]_$1=yes],
+     [bor_cv_[]_AC_LANG_ABBREV[]_$1=no])
+   ac_[]_AC_LANG_ABBREV[]_werror_flag=$bor_save_[]_AC_LANG_ABBREV[]_werror_flag])
+   []_AC_LANG_PREFIX[]FLAGS=$bor_save_[]_AC_LANG_PREFIX[]FLAGS
 ])
-
 
 # Checking characteristics of compilers and other programs
 # --------------------------------------------------------
@@ -327,81 +416,139 @@ if test "$CC" = "i586-mingw32msvc-gcc"; then
   ac_cv_c_bigendian=no
   ac_cv_sizeof_char=1
   ac_cv_sizeof_short=2
-  ac_cv_sizeof_int=4 
+  ac_cv_sizeof_int=4
   ac_cv_sizeof_long=4
   ac_cv_sizeof_long_long=4
 fi
 
-if test "$cross_compiling" = "no"
-then
-    AC_C_BIGENDIAN
-else
-#echo "CROSS ENDIAN"
-    if $CXX -v 2>&1|grep "mingw" >/dev/null 2>&1; then
-	ac_cv_c_bigendian=no
-    else
-	: # FIXME
-    fi
-#echo "CROSS ENDIAN DONE"
+# SDCC_BUILD_BIGENDIAN ([ACTION-IF-TRUE], [ACTION-IF-FALSE], [ACTION-IF-UNKNOWN])
+# -------------------------------------------------------------------------
+AC_DEFUN([SDCC_BUILD_BIGENDIAN],
+[AC_CACHE_CHECK(whether host machine byte ordering is bigendian, sdcc_cv_build_bigendian,
+[# See if sys/param.h defines the BYTE_ORDER macro.
+AC_COMPILE_IFELSE([AC_LANG_PROGRAM([#include <sys/types.h>
+#include <sys/param.h>
+],
+[#if  ! (defined BYTE_ORDER && defined BIG_ENDIAN && defined LITTLE_ENDIAN \
+	&& BYTE_ORDER && BIG_ENDIAN && LITTLE_ENDIAN)
+ bogus endian macros
+#endif
+])],
+[# It does; now see whether it defined to BIG_ENDIAN or not.
+AC_COMPILE_IFELSE([AC_LANG_PROGRAM([#include <sys/types.h>
+#include <sys/param.h>
+], [#if BYTE_ORDER != BIG_ENDIAN
+ not big endian
+#endif
+])], [sdcc_cv_build_bigendian=yes], [sdcc_cv_build_bigendian=no])],
+[# It does not; compile a test program.
+AC_RUN_IFELSE(
+[AC_LANG_PROGRAM([AC_INCLUDES_DEFAULT], [[
+  /* Are we little or big endian?  From Harbison&Steele.  */
+  union
+  {
+    long int l;
+    char c[sizeof (long int)];
+  } u;
+  u.l = 1;
+  return u.c[sizeof (long int) - 1] == 1;
+]])],
+	      [sdcc_cv_build_bigendian=no],
+	      [sdcc_cv_build_bigendian=yes],
+[# try to guess the endianness by grepping values into an object file
+  sdcc_cv_build_bigendian=unknown
+  AC_COMPILE_IFELSE([AC_LANG_PROGRAM(
+[[short int ascii_mm[] = { 0x4249, 0x4765, 0x6E44, 0x6961, 0x6E53, 0x7953, 0 };
+short int ascii_ii[] = { 0x694C, 0x5454, 0x656C, 0x6E45, 0x6944, 0x6E61, 0 };
+void _ascii () { char *s = (char *) ascii_mm; s = (char *) ascii_ii; }
+short int ebcdic_ii[] = { 0x89D3, 0xE3E3, 0x8593, 0x95C5, 0x89C4, 0x9581, 0 };
+short int ebcdic_mm[] = { 0xC2C9, 0xC785, 0x95C4, 0x8981, 0x95E2, 0xA8E2, 0 };
+void _ebcdic () { char *s = (char *) ebcdic_mm; s = (char *) ebcdic_ii; }]],
+[[ _ascii (); _ebcdic (); ]])],
+[if grep BIGenDianSyS conftest.$ac_objext >/dev/null ; then
+  sdcc_cv_build_bigendian=yes
 fi
+if grep LiTTleEnDian conftest.$ac_objext >/dev/null ; then
+  if test "$sdcc_cv_build_bigendian" = unknown; then
+    sdcc_cv_build_bigendian=no
+  else
+    # finding both strings is unlikely to happen, but who knows?
+    sdcc_cv_build_bigendian=unknown
+  fi
+fi])])])])
+case $sdcc_cv_build_bigendian in
+  yes)
+    m4_default([$1],
+      [AC_DEFINE([BUILD_WORDS_BIGENDIAN], 1,
+	[Define to 1 if your processor stores words with the most significant
+	 byte first (like Motorola and SPARC, unlike Intel and VAX).])]) ;;
+  no)
+    $2 ;;
+  *)
+    m4_default([$3],
+      [AC_MSG_ERROR([unknown endianness
+presetting sdcc_cv_build_bigendian=no (or yes) will help])]) ;;
+esac
+])# SDCC_BUILD_BIGENDIAN
 
-AC_CACHE_CHECK(whether preprocessor accepts -MM or -M,ucsim_cv_MM,
-echo "#include <stdio.h>" >_test_.c
-echo "" >>_test_.c
-$CXXCPP -v -MM _test_.c 1>&5 2>&5
-if test "$?" = "0"; then
-  ucsim_cv_MM="-MM"
-else
-  ucsim_cv_MM="-M"
-fi
-rm -f _test_.*)
-M_OR_MM=$ucsim_cv_MM
-AC_SUBST(M_OR_MM)
-
-# This is the first time when CFLAGS are set/modified!!
-
-DD_COPT(CXX, ggdb)
-DD_COPT(CXX, gstabs)
-if test "$ucsim_cv_CXXgstabs" = "yes"; then
-   gopt="-gstabs+ -g3"
-elif test "$ucsim_cv_CXXggdb" = "yes"; then
-     gopt="-ggdb -g3"
-else 
-     gopt="-g"
-fi
-if test "$CXXFLAGS"x = x ;then
-	CXXFLAGS="$gopt"
-else
-	CXXFLAGS="$CXXFLAGS $gopt"
-fi
-
-DD_COPT(CXX, pipe)
-if test "$ucsim_cv_CXXpipe" = "yes"; then
-  CXXFLAGS="$CXXFLAGS -pipe"
-fi
+SDCC_BUILD_BIGENDIAN
 
 PICOPT=""
 SHAREDLIB="no"
-DD_COPT(CXX, fPIC)
-if test "$ucsim_cv_CXXfPIC" = "yes"; then
-    PICOPT="-fPIC"
+
+if test "$ac_cv_cxx_compiler_gnu" = "yes"; then
+  AC_CACHE_CHECK(whether preprocessor accepts -MM or -M,ucsim_cv_MM,
+  echo "#include <stdio.h>" >_test_.c
+  echo "" >>_test_.c
+  $CXXCPP -v -MM _test_.c 1>&5 2>&5
+  if test "$?" = "0"; then
+    ucsim_cv_MM="-MM"
+  else
+    ucsim_cv_MM="-M"
+  fi
+  rm -f _test_.*)
+
+  # This is the first time when CFLAGS are set/modified!!
+
+  bor_IS_VALID_OPTION(ggdb)
+  bor_IS_VALID_OPTION(gstabs)
+  if test "$ucsim_cv_cxx_gstabs" = "yes"; then
+    gopt="-gstabs+ -g3"
+  elif test "$ucsim_cv_cxx_ggdb" = "yes"; then
+    gopt="-ggdb -g3"
+  else
+    gopt="-g"
+  fi
+  if test "$CXXFLAGS"x = x ;then
+    CXXFLAGS="$gopt"
+  else
+    CXXFLAGS="$CXXFLAGS $gopt"
+  fi
+
+  bor_IS_VALID_OPTION(pipe)
+  if test "$ucsim_cv_cxx_pipe" = "yes"; then
+    CXXFLAGS="$CXXFLAGS -pipe"
+  fi
+
+  MAKEDEP="$CXX $ucsim_cv_MM"
+  WALL_FLAG="-Wall"
 else
-    DD_COPT(CXX, fpic)
-    if test "$ucsim_cv_CXXfpic" = "yes"; then
-	PICOPT="-fpic"
-    fi
+  bor_IS_SUNPRO
+  if test "$bor_cv_cxx_compiler_sunpro" = "yes"; then
+    CXXFLAGS="-xO2 $CXXFLAGS"
+    MAKEDEP="$CXX -xM1"
+    WALL_FLAG=
+  fi
 fi
+
+# pic_flag is defined by AC_PROG_LIBTOOL
+PICOPT=$pic_flag
+
 if test "$PICOPT"x != "x"; then
     SHAREDLIB="yes"
 fi
-# If this is Cygwin neither use Position Independant Code
-# nor build .so
-# Quick + dirty by Bernhard
-# FIXME
-if $CXX -v 2>&1 | grep -i cygwin 1>&5 2>&5; then
-    PICOPT=""
-    SHAREDLIB="no"
-fi
+AC_SUBST(MAKEDEP)
+AC_SUBST(WALL_FLAG)
 AC_SUBST(SHAREDLIB)
 AC_SUBST(PICOPT)
 
@@ -423,13 +570,13 @@ AC_CHECK_SIZEOF(long)
 AC_CHECK_SIZEOF(long long)
 else
     if $CXX -v 2>&1|grep "mingw" >/dev/null 2>&1; then
-	ac_cv_sizeof_char=1
-	ac_cv_sizeof_short=2
-	ac_cv_sizeof_int=4 
-	ac_cv_sizeof_long=4
-	ac_cv_sizeof_long_long=4
+        ac_cv_sizeof_char=1
+        ac_cv_sizeof_short=2
+        ac_cv_sizeof_int=4
+        ac_cv_sizeof_long=4
+        ac_cv_sizeof_long_long=4
     else
-	: # FIXME
+        : # FIXME
     fi
 #echo
 fi
@@ -437,24 +584,24 @@ fi
 type_name()
 {
     if expr "$ac_cv_sizeof_char" '>=' "$1" >/dev/null; then
-	echo "char"
-	exit
+        echo "char"
+        exit
     fi
     if expr "$ac_cv_sizeof_short" '>=' "$1" >/dev/null; then
-	echo "short"
-	exit
+        echo "short"
+        exit
     fi
     if expr "$ac_cv_sizeof_int" '>=' "$1" >/dev/null; then
-	echo "int"
-	exit
+        echo "int"
+        exit
     fi
     if expr "$ac_cv_sizeof_long" '>=' "$1" >/dev/null; then
-	echo "long"
-	exit
+        echo "long"
+        exit
     fi
     if expr "$ac_cv_sizeof_long_long" '>=' "$1" >/dev/null; then
-	echo "long long"
-	exit
+        echo "long long"
+        exit
     fi
     echo "long long"
 }
@@ -491,7 +638,8 @@ AC_DEFINE_UNQUOTED(_M_, "${M}")
 # Generating output files
 # ===========================================================================
 
-AC_OUTPUT(main.mk:main_in.mk
+AC_OUTPUT(Makefile
+main.mk:main_in.mk
 packages.mk:packages_in.mk
 sim.src/Makefile
 cmd.src/Makefile
